
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141202 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintactico_1 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return tabla_simbolos.class;
}

  /** Default constructor. */
  public sintactico_1() {super();}

  /** Constructor which sets the default scanner. */
  public sintactico_1(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintactico_1(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\025\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\004\010\000\002\005\007\000\002\005\005" +
    "\000\002\005\007\000\002\005\005\000\002\007\012\000" +
    "\002\007\012\000\002\010\007\000\002\010\005\000\002" +
    "\010\007\000\002\010\005\000\002\006\007\000\002\006" +
    "\007\000\002\006\007\000\002\006\007\000\002\006\007" +
    "\000\002\006\007\000\002\006\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\117\000\004\004\006\001\002\000\004\002\000\001" +
    "\002\000\004\002\121\001\002\000\004\006\007\001\002" +
    "\000\006\021\012\023\013\001\002\000\004\005\011\001" +
    "\002\000\004\002\uffff\001\002\000\006\012\071\013\073" +
    "\001\002\000\006\012\071\013\073\001\002\000\004\007" +
    "\015\001\002\000\004\010\016\001\002\000\006\021\017" +
    "\023\021\001\002\000\020\012\022\013\030\014\025\015" +
    "\023\016\024\017\027\022\uffed\001\002\000\004\011\064" +
    "\001\002\000\020\012\022\013\030\014\025\015\023\016" +
    "\024\017\027\024\uffed\001\002\000\004\032\060\001\002" +
    "\000\004\032\054\001\002\000\004\032\050\001\002\000" +
    "\004\032\044\001\002\000\004\024\041\001\002\000\004" +
    "\032\035\001\002\000\004\032\031\001\002\000\004\034" +
    "\032\001\002\000\004\030\033\001\002\000\022\012\022" +
    "\013\030\014\025\015\023\016\024\017\027\022\uffed\024" +
    "\uffed\001\002\000\006\022\ufff3\024\ufff3\001\002\000\004" +
    "\033\036\001\002\000\004\030\037\001\002\000\022\012" +
    "\022\013\030\014\025\015\023\016\024\017\027\022\uffed" +
    "\024\uffed\001\002\000\006\022\uffee\024\uffee\001\002\000" +
    "\006\011\ufff4\031\042\001\002\000\006\021\017\023\021" +
    "\001\002\000\004\011\ufff5\001\002\000\004\034\045\001" +
    "\002\000\004\030\046\001\002\000\022\012\022\013\030" +
    "\014\025\015\023\016\024\017\027\022\uffed\024\uffed\001" +
    "\002\000\006\022\ufff1\024\ufff1\001\002\000\004\033\051" +
    "\001\002\000\004\030\052\001\002\000\022\012\022\013" +
    "\030\014\025\015\023\016\024\017\027\022\uffed\024\uffed" +
    "\001\002\000\006\022\uffef\024\uffef\001\002\000\004\033" +
    "\055\001\002\000\004\030\056\001\002\000\022\012\022" +
    "\013\030\014\025\015\023\016\024\017\027\022\uffed\024" +
    "\uffed\001\002\000\006\022\ufff0\024\ufff0\001\002\000\004" +
    "\020\061\001\002\000\004\030\062\001\002\000\022\012" +
    "\022\013\030\014\025\015\023\016\024\017\027\022\uffed" +
    "\024\uffed\001\002\000\006\022\ufff2\024\ufff2\001\002\000" +
    "\004\005\ufffe\001\002\000\004\022\066\001\002\000\006" +
    "\011\ufff6\031\067\001\002\000\006\021\017\023\021\001" +
    "\002\000\004\011\ufff7\001\002\000\004\032\106\001\002" +
    "\000\004\024\103\001\002\000\004\032\074\001\002\000" +
    "\004\034\075\001\002\000\004\030\076\001\002\000\004" +
    "\012\077\001\002\000\004\032\100\001\002\000\004\020" +
    "\101\001\002\000\004\030\102\001\002\000\006\022\ufff9" +
    "\024\ufff9\001\002\000\006\007\ufffa\031\104\001\002\000" +
    "\006\021\012\023\013\001\002\000\004\007\ufffb\001\002" +
    "\000\004\020\107\001\002\000\004\030\110\001\002\000" +
    "\004\013\111\001\002\000\004\032\112\001\002\000\004" +
    "\034\113\001\002\000\004\030\114\001\002\000\006\022" +
    "\ufff8\024\ufff8\001\002\000\004\022\116\001\002\000\006" +
    "\007\ufffc\031\117\001\002\000\006\021\012\023\013\001" +
    "\002\000\004\007\ufffd\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\117\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\007\001\001\000\004" +
    "\005\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\114\001\001\000\004\007\071\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\017\001\001\000" +
    "\004\006\064\001\001\000\002\001\001\000\004\006\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\033\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\037\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\042\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\046\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\052\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\006\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\062\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\067\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\104\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\117\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintactico_1$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintactico_1$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintactico_1$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



/**Metodo al que se llama automáticamente ante algún error sintactico.*/
public static proyecto1_compi1.Objeto o=new proyecto1_compi1.Objeto();
public void syntax_error(Symbol s){
System.out.println("Error en la Línea " + (s.right+1) +" Columna " +s.left+ ". Identificador " +s.value + " no reconocido." );
}
/**Metodo al que se llama en el momento en que ya no es posible una recuperación de errores.*/
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
System.out.println("Error en la Línea " + (s.right+1)+ "Columna "+s.left+". Identificador " + s.value + " no reconocido.");
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintactico_1$actions {
  private final sintactico_1 parser;

  /** Constructor */
  CUP$sintactico_1$actions(sintactico_1 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintactico_1$do_action_part00000000(
    int                        CUP$sintactico_1$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_1$parser,
    java.util.Stack            CUP$sintactico_1$stack,
    int                        CUP$sintactico_1$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintactico_1$result;

      /* select the action based on the action number */
      switch (CUP$sintactico_1$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).value;
		RESULT = start_val;
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintactico_1$parser.done_parsing();
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIA ::= A 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("INICIA",0, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= Oconf B Cconf 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // B ::= Ofondo C Cfondo Odis F Cdis 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("B",2, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // C ::= Ollave E Cllave tcom C 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // C ::= Ollave E Cllave 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // C ::= Ocorch E Ccorch tcom C 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // C ::= Ocorch E Ccorch 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // E ::= tnomb tigual tlnombre tpuntycom tpath tigual tlpath tpuntycom 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).value;
		proyecto1_compi1.Fondo f=new  proyecto1_compi1.Fondo();
			f.nombre=a.toString();
			f.path=b.toString();
		 proyecto1_compi1.Main.fondos.add(f);
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-7)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // E ::= tpath tigual tlpath tpuntycom tnomb tigual tlnombre tpuntycom 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-5)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-1)).value;
		proyecto1_compi1.Fondo f=new  proyecto1_compi1.Fondo();
			f.nombre=a.toString();
			f.path=b.toString();
		 proyecto1_compi1.Main.fondos.add(f);
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-7)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // F ::= Ollave D Cllave tcom F 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("F",6, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // F ::= Ollave D Cllave 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("F",6, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // F ::= Ocorch D Ccorch tcom F 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("F",6, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // F ::= Ocorch D Ccorch 
            {
              Object RESULT =null;

              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("F",6, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // D ::= tnomb tigual tlnombre tpuntycom D 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.nombre=a.toString();
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // D ::= tpath tigual tlpath tpuntycom D 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.path=b.toString();
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // D ::= ttipo tigual tlnombre tpuntycom D 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.tipo=c.toString();
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // D ::= tpuntos tigual tnumero tpuntycom D 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.puntos=Integer.parseInt(d.toString());
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // D ::= tcreci tigual tnumero tpuntycom D 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.crecimiento=Integer.parseInt(e.toString());
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // D ::= ttiempo tigual tnumero tpuntycom D 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-2)).value;
		o.tiempo=Integer.parseInt(f.toString());
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.elementAt(CUP$sintactico_1$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // D ::= 
            {
              Object RESULT =null;
		proyecto1_compi1.Main.objetos.add(o);
	o=new proyecto1_compi1.Objeto();
              CUP$sintactico_1$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_1$stack.peek()), RESULT);
            }
          return CUP$sintactico_1$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintactico_1$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintactico_1$do_action(
    int                        CUP$sintactico_1$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_1$parser,
    java.util.Stack            CUP$sintactico_1$stack,
    int                        CUP$sintactico_1$top)
    throws java.lang.Exception
    {
              return CUP$sintactico_1$do_action_part00000000(
                               CUP$sintactico_1$act_num,
                               CUP$sintactico_1$parser,
                               CUP$sintactico_1$stack,
                               CUP$sintactico_1$top);
    }
}

}
