
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141202 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintactico_3 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return tabla_simbolos3.class;
}

  /** Default constructor. */
  public sintactico_3() {super();}

  /** Constructor which sets the default scanner. */
  public sintactico_3(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintactico_3(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\004\005\000\002\005\007\000\002\005\005" +
    "\000\002\007\007\000\002\011\002\000\002\006\011\000" +
    "\002\010\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\004\007\006\001\002\000\004\002\000\001" +
    "\002\000\004\002\035\001\002\000\004\004\007\001\002" +
    "\000\004\013\012\001\002\000\004\010\011\001\002\000" +
    "\004\002\uffff\001\002\000\004\007\013\001\002\000\004" +
    "\016\015\001\002\000\004\010\ufffe\001\002\000\004\013" +
    "\022\001\002\000\004\010\017\001\002\000\006\010\ufffc" +
    "\014\020\001\002\000\004\007\013\001\002\000\004\010" +
    "\ufffd\001\002\000\004\007\023\001\002\000\004\006\024" +
    "\001\002\000\004\013\027\001\002\000\004\010\026\001" +
    "\002\000\004\010\ufffb\001\002\000\004\011\030\001\002" +
    "\000\004\005\031\001\002\000\004\012\032\001\002\000" +
    "\004\010\ufffa\001\002\000\004\010\ufff8\001\002\000\004" +
    "\010\ufff9\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\006\002\004\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\007\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\013\001\001\000\004\007\015\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\020\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\024\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\032\001\001\000\004\010" +
    "\033\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintactico_3$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintactico_3$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintactico_3$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



/**Metodo al que se llama automáticamente ante algún error sintactico.*/
public static proyecto1_compi1.Estrategias est;
public static String movis="";
public void syntax_error(Symbol s){
System.out.println("Error en la Línea " + (s.right+1) +" Columna " +s.left+ ". Identificador " +s.value + " no reconocido." );
}
/**Metodo al que se llama en el momento en que ya no es posible una recuperación de errores.*/
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
System.out.println("Error en la Línea " + (s.right+1)+ "Columna "+s.left+". Identificador " + s.value + " no reconocido.");
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintactico_3$actions {
  private final sintactico_3 parser;

  /** Constructor */
  CUP$sintactico_3$actions(sintactico_3 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintactico_3$do_action_part00000000(
    int                        CUP$sintactico_3$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_3$parser,
    java.util.Stack            CUP$sintactico_3$stack,
    int                        CUP$sintactico_3$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintactico_3$result;

      /* select the action based on the action number */
      switch (CUP$sintactico_3$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).value;
		RESULT = start_val;
              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintactico_3$parser.done_parsing();
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIA ::= A 
            {
              Object RESULT =null;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("INICIA",0, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // A ::= Ollave B Cllave 
            {
              Object RESULT =null;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("A",1, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // B ::= test tpunts C 
            {
              Object RESULT =null;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("B",2, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // C ::= Ollave E Cllave tcom C 
            {
              Object RESULT =null;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // C ::= Ollave E Cllave 
            {
              Object RESULT =null;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("C",3, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // E ::= tlnombre tpunts Ollave D Cllave 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-4)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-4)).value;
		est.nombre=a.toString();
              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("E",5, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$0 ::= 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).value;
movis=b.toString();
              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("NT$0",7, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // D ::= tmovs tpunts Ocorch tCmovs Ccorch NT$0 F 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-3)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-3)).value;

              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("D",4, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.elementAt(CUP$sintactico_3$top-6)), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // F ::= 
            {
              Object RESULT =null;
		est=new proyecto1_compi1.Estrategias(movis);proyecto1_compi1.Main.estrats.add(est);
              CUP$sintactico_3$result = parser.getSymbolFactory().newSymbol("F",6, ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_3$stack.peek()), RESULT);
            }
          return CUP$sintactico_3$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintactico_3$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintactico_3$do_action(
    int                        CUP$sintactico_3$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_3$parser,
    java.util.Stack            CUP$sintactico_3$stack,
    int                        CUP$sintactico_3$top)
    throws java.lang.Exception
    {
              return CUP$sintactico_3$do_action_part00000000(
                               CUP$sintactico_3$act_num,
                               CUP$sintactico_3$parser,
                               CUP$sintactico_3$stack,
                               CUP$sintactico_3$top);
    }
}

}
