
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos3 {
  /* terminals */
  public static final int Ollave = 5;
  public static final int tCmovs = 3;
  public static final int EOF = 0;
  public static final int Cllave = 6;
  public static final int tnumero = 11;
  public static final int Ocorch = 7;
  public static final int tmovs = 4;
  public static final int Ccorch = 8;
  public static final int test = 2;
  public static final int error = 1;
  public static final int tlnombre = 12;
  public static final int tpunts = 9;
  public static final int tcom = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "test",
  "tCmovs",
  "tmovs",
  "Ollave",
  "Cllave",
  "Ocorch",
  "Ccorch",
  "tpunts",
  "tcom",
  "tnumero",
  "tlnombre"
  };
}

