
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int Oconf = 2;
  public static final int tpath = 8;
  public static final int tgionb = 19;
  public static final int tpuntos = 11;
  public static final int tdiag = 20;
  public static final int Odis = 6;
  public static final int tnomb = 9;
  public static final int tpuntycom = 22;
  public static final int tcom = 23;
  public static final int tlpath = 14;
  public static final int tlnombre = 26;
  public static final int Ofondo = 4;
  public static final int Cfondo = 5;
  public static final int EOF = 0;
  public static final int Cdis = 7;
  public static final int ttiempo = 13;
  public static final int tcreci = 12;
  public static final int tpunts = 21;
  public static final int Ocorch = 17;
  public static final int ttipo = 10;
  public static final int Ccorch = 18;
  public static final int error = 1;
  public static final int tnumero = 25;
  public static final int Cconf = 3;
  public static final int tigual = 24;
  public static final int Ollave = 15;
  public static final int Cllave = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Oconf",
  "Cconf",
  "Ofondo",
  "Cfondo",
  "Odis",
  "Cdis",
  "tpath",
  "tnomb",
  "ttipo",
  "tpuntos",
  "tcreci",
  "ttiempo",
  "tlpath",
  "Ollave",
  "Cllave",
  "Ocorch",
  "Ccorch",
  "tgionb",
  "tdiag",
  "tpunts",
  "tpuntycom",
  "tcom",
  "tigual",
  "tnumero",
  "tlnombre"
  };
}

