
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos2 {
  /* terminals */
  public static final int Oven = 14;
  public static final int Oparen = 21;
  public static final int Cparen = 22;
  public static final int tfondo = 18;
  public static final int tancho = 19;
  public static final int Cven = 15;
  public static final int Oest = 8;
  public static final int tdpunt = 24;
  public static final int Opared = 4;
  public static final int Cpared = 5;
  public static final int Obon = 10;
  public static final int Obom = 16;
  public static final int tpuntycom = 25;
  public static final int tcom = 26;
  public static final int tlnombre = 29;
  public static final int Oex = 6;
  public static final int Cest = 9;
  public static final int Cesce = 3;
  public static final int EOF = 0;
  public static final int Cbon = 11;
  public static final int Cbom = 17;
  public static final int error = 1;
  public static final int tnumero = 28;
  public static final int Oman = 12;
  public static final int tigual = 27;
  public static final int talto = 20;
  public static final int Cex = 7;
  public static final int Oesce = 2;
  public static final int Cman = 13;
  public static final int Ctag = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Oesce",
  "Cesce",
  "Opared",
  "Cpared",
  "Oex",
  "Cex",
  "Oest",
  "Cest",
  "Obon",
  "Cbon",
  "Oman",
  "Cman",
  "Oven",
  "Cven",
  "Obom",
  "Cbom",
  "tfondo",
  "tancho",
  "talto",
  "Oparen",
  "Cparen",
  "Ctag",
  "tdpunt",
  "tpuntycom",
  "tcom",
  "tigual",
  "tnumero",
  "tlnombre"
  };
}

