
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos3 {
  /* terminals */
  public static final int Oparen = 5;
  public static final int tfunc = 2;
  public static final int Cparen = 6;
  public static final int Ollave = 3;
  public static final int tlnumero = 9;
  public static final int EOF = 0;
  public static final int Cllave = 4;
  public static final int error = 1;
  public static final int tlnombre = 10;
  public static final int tpunts = 7;
  public static final int tcom = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tfunc",
  "Ollave",
  "Cllave",
  "Oparen",
  "Cparen",
  "tpunts",
  "tcom",
  "tlnumero",
  "tlnombre"
  };
}

