
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos2 {
  /* terminals */
  public static final int tcolum = 2;
  public static final int tletra = 3;
  public static final int Ollave = 4;
  public static final int EOF = 0;
  public static final int Cllave = 5;
  public static final int tnumero = 9;
  public static final int Ocorch = 6;
  public static final int tcasi = 12;
  public static final int Ccorch = 7;
  public static final int error = 1;
  public static final int tlnombre = 10;
  public static final int tpunts = 11;
  public static final int tcom = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tcolum",
  "tletra",
  "Ollave",
  "Cllave",
  "Ocorch",
  "Ccorch",
  "tcom",
  "tnumero",
  "tlnombre",
  "tpunts",
  "tcasi"
  };
}

